### ISSUE TITLE
Un-consistency in unit test test_bit_length_create_commitment

### ISSUE THREAD

**Issue by gbenattar** [KZen-networks/multi-party-ecdsa#17]
To reproduce, in: multi-party-ecdsa/src/cryptographic_primitives/commitments/hash_commitment.rs, you can add a for loop in the test itself:

```rust
    #[test]
    fn test_bit_length_create_commitment() {
        for _ in 1..100 {
            let message = BigInt::sample(SECURITY_BITS);
            let (commitment, blind_factor) = HashCommitment::create_commitment(&message);
            //test commitment length  - works because SHA256 output length the same as sec_bits
            assert_eq!(commitment.to_str_radix(16).len(), SECURITY_BITS / 4);
            assert_eq!(blind_factor.to_str_radix(16).len(), SECURITY_BITS / 4);
        }
    }
```

```
---- cryptographic_primitives::commitments::hash_commitment::tests::test_bit_length_create_commitment stdout ----
	thread 'cryptographic_primitives::commitments::hash_commitment::tests::test_bit_length_create_commitment' panicked at 'assertion failed: `(left == right)`
  left: `63`,
 right: `64`', src/cryptographic_primitives/commitments/hash_commitment.rs:69:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:

```

**Comment by omershlo** [comment]
good catch. its the same issue with `sample` . I changed the test accordingly.

**Comment by gbenattar** [comment]
Issue is still present:

```rust
---- cryptographic_primitives::commitments::hash_commitment::tests::test_bit_length_create_commitment stdout ----
	thread 'cryptographic_primitives::commitments::hash_commitment::tests::test_bit_length_create_commitment' panicked at 'assertion failed: `(left == right)`
  left: `63`,
 right: `64`', src/cryptographic_primitives/commitments/hash_commitment.rs:68:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:205
   3: std::panicking::default_hook
             at libstd/panicking.rs:215
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:457
   5: std::panicking::try::do_call
             at libstd/panicking.rs:344
   6: multi_party_ecdsa::cryptographic_primitives::commitments::hash_commitment::tests::test_bit_length_create_commitment
             at src/cryptographic_primitives/commitments/hash_commitment.rs:68
   7: multi_party_ecdsa::__test::TESTS::{{closure}}
             at src/cryptographic_primitives/commitments/hash_commitment.rs:64
   8: core::ops::function::FnOnce::call_once
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
   9: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
             at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:637
  10: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105
```

**Comment by omershlo** [comment]
you are referring to a different bug. I changed the code to handle both of them. 
I test now the probability distribution of the bit length. It can still fail but with very very small probability

**Comment by omershlo** [comment]
@gbenattar can you check that its ok now please?

**Comment by gbenattar** [comment]
LGTM. Closing
