### ISSUE TITLE
thread 'test_two_party_keygen' panicked at 'assertion failed'

### ISSUE THREAD

**Issue by gbenattar** [KZen-networks/multi-party-ecdsa#37]
Run with: `seq 50 | xargs -Iz cargo test`:

```
---- test_two_party_keygen stdout ----
thread 'test_two_party_keygen' panicked at 'assertion failed: party_two::PaillierPublic::verify_range_proof(&party_two_paillier, &challenge,
                                              &encrypted_pairs, &proof)', tests/keygen_integ_test.rs:53:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:475
   5: secp256k1_sha256_transform
             at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:409
   6: keygen_integ_test::test_two_party_keygen
             at tests/keygen_integ_test.rs:53
   7: keygen_integ_test::__test::TESTS::{{closure}}
             at tests/keygen_integ_test.rs:8
   8: core::ops::function::FnOnce::call_once
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
   9: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1454
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
             at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:640
  10: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:106


failures:
    test_two_party_keygen

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by gbenattar** [comment]
Fixed by https://github.com/KZen-networks/cryptography-utils/commit/d6eefa46a8d46ede5ada1684edaf85e88d1502f1.
