### ISSUE TITLE
test_d_log_proof_party_two_party_one' panicked at 'assertion failed: party_two_seco nd_message.d_log_proof_result.is_ok()'

### ISSUE THREAD

**Issue by gbenattar** [KZen-networks/multi-party-ecdsa#38]
Run with: `seq 50 | xargs -Iz cargo test`:

```
failures:

---- protocols::two_party_ecdsa::lindell_2017::test::tests::test_d_log_proof_party_two_party_one stdout ----
thread 'protocols::two_party_ecdsa::lindell_2017::test::tests::test_d_log_proof_party_two_party_one' panicked at 'assertion failed: party_two_seco
nd_message.d_log_proof_result.is_ok()', src/protocols/two_party_ecdsa/lindell_2017/test.rs:26:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:475
   5: secp256k1_sha256_transform
             at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:409
   6: multi_party_ecdsa::protocols::two_party_ecdsa::lindell_2017::test::tests::test_d_log_proof_party_two_party_one
             at src/protocols/two_party_ecdsa/lindell_2017/test.rs:26
   7: multi_party_ecdsa::__test::TESTS::{{closure}}
             at src/protocols/two_party_ecdsa/lindell_2017/test.rs:9
   8: core::ops::function::FnOnce::call_once
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
   9: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1454
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
             at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:640
  10: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:106


failures:
    protocols::two_party_ecdsa::lindell_2017::test::tests::test_d_log_proof_party_two_party_one

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by gbenattar** [comment]
Full stack trace:

```
---- test_two_party_sign stdout ----
thread 'test_two_party_sign' panicked at 'Party two DLog proved.: ProofError', libcore/result.rs:945:5
stack backtrace:
   0:        0x10e12309f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h47054aa11663b182
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:        0x10e11464a - std::sys_common::backtrace::print::h7e9fdf2e0eb4c7cb
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:        0x10e1258a3 - std::panicking::default_hook::{{closure}}::hd5ad4a362ab44a19
                               at libstd/panicking.rs:211
   3:        0x10e1255ce - std::panicking::default_hook::h7e35894cc8a4634b
                               at libstd/panicking.rs:221
   4:        0x10e125f97 - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::h76ca41ba1a7ff5fa
                               at libstd/panicking.rs:475
   5:        0x10e125b3c - std::panicking::continue_panic_fmt::h4f0ff5bda1044263
                               at libstd/panicking.rs:390
   6:        0x10e125a28 - std::panicking::try::do_call::h3e9888c79bb76760
                               at libstd/panicking.rs:325
   7:        0x10e160311 - core::ptr::drop_in_place::h003bf7dea51b0b30
                               at libcore/panicking.rs:77
   8:        0x10e0343cb - core::result::unwrap_failed::h606bd3afea6579f9
                               at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:26
   9:        0x10e034265 - <core::result::Result<T, E>>::expect::hd1b959092b527c36
                               at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:809
  10:        0x10e03455d - signing_integ_test::test_two_party_sign::h9c5a9ba35c4291e7
                               at tests/signing_integ_test.rs:38
  11:        0x10e0350f0 - signing_integ_test::__test::TESTS::{{closure}}::hd3454c11e5eee5d7
                               at tests/signing_integ_test.rs:8
  12:        0x10e0347e0 - core::ops::function::FnOnce::call_once::h4c8040298dcf3470
                               at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
  13:        0x10e092a01 - <F as alloc::boxed::FnBox<A>>::call_box::hb6071f2db28f5749
                               at libtest/lib.rs:1454
                               at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
                               at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:640
  14:        0x10e13207e - panic_unwind::dwarf::eh::read_encoded_pointer::hb1836e60a7701de2
                               at libpanic_unwind/lib.rs:106
  15:        0x10e0b39bc - std::sys_common::backtrace::__rust_begin_short_backtrace::hea0648d4043f924f
                               at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:289
                               at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:392
                               at libtest/lib.rs:1409
                               at /Users/travis/build/rust-lang/rust/src/libstd/sys_common/backtrace.rs:136
  16:        0x10e0b4307 - std::panicking::try::do_call::h783d73be4e903597
                               at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:409
                               at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:313
                               at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:310
  17:        0x10e13207e - panic_unwind::dwarf::eh::read_encoded_pointer::hb1836e60a7701de2
                               at libpanic_unwind/lib.rs:106
  18:        0x10e0a7964 - <F as alloc::boxed::FnBox<A>>::call_box::h7a36f280e32ce2ea
                               at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:289
                               at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:392
                               at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:408
                               at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:640
  19:        0x10e11368b - std::sys::unix::thread::Thread::new::thread_start::h7526a71788d4aee9
                               at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:650
                               at libstd/sys_common/thread.rs:24
                               at libstd/sys/unix/thread.rs:90
  20:     0x7fff87657059 - _pthread_body
  21:     0x7fff87656fd6 - _pthread_start


failures:
    test_two_party_sign

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by gbenattar** [comment]
Fixed by: https://github.com/KZen-networks/cryptography-utils/commit/d6eefa46a8d46ede5ada1684edaf85e88d1502f1
